## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
git:
  depth: 99999999
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
# matrix:
#  allow_failures:
#  - julia: nightly

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TableShowUtils")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
